version: "3.1"

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootuser

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootuser
      ME_CONFIG_MONGODB_URL: mongodb://rootuser:rootuser@mongo:27017/
    restart: always
    ports:
      - "8081:8081"

volumes:
  data: {}